Feenzy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('Homepage.urls', namespace='story1')),
    path('', include('personalwebsite.urls', namespace='personalwebsite')),
    path('matkul/', include('matkul.urls', namespace ='matkul')),
]

Homepage/urls.py
from django.urls import path
from . import views

app_name = 'Homepage'
 
urlpatterns = [
    path('story1/', views.story1, name='story1')
]

matkul/urls.py
from django.urls import path
from . import views

app_name = 'matkul'

urlpatterns = [
    path('matkul',views.listMatkul,name='listMatkul'),
    path('TambahkanMatkul',views.add, name='addMatkul'),
    path('delete/P<int:delete_id>/',views.delete, name='delete'),
]

personalwebsite/urls.py
from django.urls import path
from . import views

app_name = 'personalwebsite'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('profil/', views.profile, name='profile'),
    path('experience/', views.experience, name='experience')
]

Homepage/models.py
from django.db import models

# Create your models here.

matkul/models.py
from django.db import models

# Create your models here.

class PostModel(models.Model):
    nama_matkul = models.CharField(max_length = 100)
    nama_dosen = models.CharField(max_length=100)
    jumlah_sks = models.IntegerField()
    semester = models.CharField(max_length = 100)
    ruang_kelas = models.CharField(max_length = 100)
    deskripsi = models.CharField(max_length = 100, null = True)
    
    def __str__(self):
        return "{}.{}".format(self.id, self.nama_matkul)

personalwebsite/models.py
from django.db import models

# Create your models here.

matkul/forms.py
from django import forms
from .models import PostModel


class MatkulForm(forms.Form):
    nama_matkul = forms.CharField(
        label = "Nama Mata Kuliah",
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    nama_dosen = forms.CharField(
    label = "Nama Dosen",
    max_length = 100,
    widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    jumlah_sks = forms.IntegerField(
        label = "Jumlah SKS",
        widget = forms.NumberInput(
            attrs={
                'class':'form-control',
                'min':'1',
                'max':'6',
                'type':'number'
            }
        )
    )
    semester = forms.CharField(
    label = "Semester Tahun",
    max_length = 100,
    widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    ruang_kelas = forms.CharField(
    label = "Ruang Kelas",
    max_length = 100,
    widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    deskripsi = forms.CharField(
    label = "Deskripsi",
    max_length = 100,
    widget = forms.Textarea(
            attrs={
                'class':'form-control',
            }
        )
    )

Homepage/views.py
from django.shortcuts import render
# Create your views here.
def story1(request):
    return render(request, "story1.html")

matkul/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import MatkulForm
from .models import PostModel
# Create your views here.

def delete(request,delete_id):
	PostModel.objects.filter(id=delete_id).delete()
	return redirect('matkul:matkul')
    
def listMatkul(request):
    posts = PostModel.objects.all()
    context = {
        'page_title':'List Mata Kuliah',
        'posts':posts,
    }
    return render(request, 'matkul/listMatkul.html',context)

def add(request):
    matkul_form = MatkulForm(request.POST or None)

    if matkul_form.is_valid():
        if request.method == 'POST':
            PostModel.objects.create(
                nama_matkul = matkul_form.cleaned_data.get('nama_matkul'),
                nama_dosen = matkul_form.cleaned_data.get('nama_dosen'),
                jumlah_sks = matkul_form.cleaned_data.get('jumlah_sks'),
                semester = matkul_form.cleaned_data.get('semester'),
                ruang_kelas = matkul_form.cleaned_data.get('ruang_kelas'),
                deskripsi = matkul_form.cleaned_data.get('deskripsi'),
                )
            return HttpResponseRedirect("/matkul/matkul")

            

    context = {
        'page_title':'Tambahkan Mata Kuliah',
        'matkul_form':matkul_form,
    }
    return render(request, 'matkul/addMatkul.html', context)
    

personalwebsite/views.py
from django.shortcuts import render

# Create your views here.

def welcome(request):
    return render(request, 'personalwebsite/welcome.html')

def profile(request):
    return render(request, 'personalwebsite/profile.html')

def experience(request):
    return render(request, 'personalwebsite/experience.html')

Homepage/templates/story1.html
{% load static %}
<html>
	<head>
		<title>Story 1 PPW (Profil)</title>
		<style>
			.content {
					justify-content: center;
					vertical-align: middle;
  					max-width: 500px;
  					margin: auto;
			}
			table, th, td {
  				border: 1px solid black;
			}

			body {
				background-image: url("{% static 'w.jpg' %}");
				background-repeat: no-repeat;
				background-size: cover;
			}

			.button {
            border: none;
            color: rgb(255, 255, 255);
            padding: 10px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            transition-duration: 0.4s;
            cursor: pointer;
            display: block;
            margin-left: auto;
            margin-right: auto;
            }

            .button {
            background-color: rgb(147, 216, 248);
            color: rgb(255, 255, 255);
            border: 4px solid #690041;
            }

            .button:hover {
            background-color: #3cb9f3;
            color: white;
            }

            .button a {
                color: rgb(255, 255, 255);
            }
		</style>
	</head>
	<body>
		<h1 align= "center"> Profil </h1>

		<div class="content">
		<br>
		<center><img src="{% static 'MY20.jpg' %}" alt="Foto Profil" width="282" height="358.5" ></center>
		<p> <b> Nama </b>: Futuh Nurmuntaha Alfahmi</p>
		<p> <b> TTL </b>: Garut, 06 September 2001</p>
		<p> <b> NPM </b>: 1906305801</p>
		<p> <b> Angkatan </b>: 2019</p>
		<p> <b> Pekerjaan </b>: Mahasiswa di Fakultas Ilmu Komputer, Universitas Indonesia</p>
		<p> <b> Hobi </b>: Bermain Game dan Menonton Youtube</p>
		<p> <b> Deskripsi Singkat </b>: Saya adalah seorang mahasiswa biasa yang tak sempurna dan kadang salah.</p>
		
		<center>
		<p> <b> Riwayat Pendidikan </b>:</p>

		<table>
			<tr>
				<th> <b> Tahun </b> </th>
				<th> <b> Nama Sekolah </b> </th>
			</tr>
			<tr>
				<td> 2019-Sekarang </td>
				<td> Universitas Indonesia </td>
			</tr>
			<tr>
				<td> 2016-2019 </td>
				<td> SMAN 1 Kota Bogor </td>
			</tr>
			<tr>
				<td> 2013-2016 </td>
				<td> SMPIT Ummul Quro Bogor </td>
			</tr>
			<tr>
				<td> 2007-2013 </td>
				<td> SDIT Aliya </td>
			</tr>
		</table>

		<br>

		<p> <b> Kontak Saya </b>:</p>

		<a href="https://www.instagram.com/funura/">
		<img src="{% static 'instagram.png' %}" alt="instagram" style="width: 3rem"/>
		</a>
		<a href="https://www.facebook.com/futuh.nurmuntahaalfahmi">
		<img src="{% static 'facebook.png' %}" alt="facebook" style="width: 3rem"/>
		</a>
		<a href="https://www.linkedin.com/in/futuh-nurmuntaha-alfahmi-4841201a3/">
		<img src="{% static 'linkedin.png' %}" alt="linkedin" style="width: 3rem"/>
		</a>

		<button class="button"><a href="{% url 'personalwebsite:welcome' %}">Story 3 !</a></button><br>

		</center>
		</div>
	</body>

matkul/templates/matkul/addMatkul.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <!-- Font -->
  
    <style>
        body {
            background-color: #00a2ff;
        }
        a {
            color: rgb(20, 11, 11);
        }
        #back a{
            color: brown;
        }
        #list a{
            color: aliceblue;
        }
    </style>
    <title>Add Schedule</title>
  </head>
  <body>
        
    
    <div class="row mt-2 mb-3 justify-content-center">
        <div class="col text-center">
          <button id="back" type="button" class="btn btn-outline-seconadry"><a href="{% url 'personalwebsite:welcome' %}">Kembali ke halaman utama</a></button>
        </div>
    </div>
        
        <div class="row mt-3 mb-3">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="card">
                    <h5 class="card-header">Tambah Mata kuliah</h5>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                    
                            {{matkul_form.label_tag}}
                            {{matkul_form}}
                            <br>
                            <button type="submit">Tambah Jadwal</button>
            
                        </form>            
                    </div>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
        <div class="row mb-3 justify-content-center">
            <div class="col text-center">
              <button id="list" type="button" class="btn btn-dark"><a href="{% url 'matkul:listMatkul' %}">Lihat daftar mata kuliah</a></button>
            </div>
        </div>
      
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

matkul/templates/matkul/listMatkul.html
{%load static%}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <!-- Font -->

    <style>
      body {
        background-color: #7ae0ff;
      }
      a {
      color: rgb(255, 255, 255);
      }
      #back a{
        color: rgb(0, 0, 0);
      }
    </style>

    <title>List Mata Kuliah</title>
  </head>
  <body>

    <div class="row mt-2 mb-3 justify-content-center">
      <div class="col text-center">
        <button id="back" type="button" class="btn btn-outline-secondary"><a href="{% url 'personalwebsite:welcome' %}">Back to main page</a></button>
      </div>
    </div>

    <br>

    <h1 style="text-align: center;">{{page_title}}</h1>
    <div class="row mt-2 mb-3">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <table class="table">
                <thead class="thead-dark">
                    <th scope="col">Nama Matkul</th>
                    <th scope="col">Nama Dosen</th>
                    <th scope="col">Jumlah SKS</th>
                    <th scope="col">Semester</th>
                    <th scope="col">Ruang Kelas</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Hapus</th>
                </thead>
                <tbody>
                    {% for obj in posts %}
                    <tr>
                        <th>{{obj.nama_matkul}}</th>
                        <th>{{obj.nama_dosen}}</th>
                        <th>{{obj.jumlah_sks}}</th>
                        <th>{{obj.semester}}</th>
                        <th>{{obj.ruang_kelas}}</th>
                        <th>{{obj.deskripsi}}</th>
                        <th><a class="btn btn-warning" href="{% url 'matkul:delete' obj.id  %}">Delete</a></th>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="col-md-1"></div>
  </div>
  <div class="row mb-3 justify-content-center">
    <div class="col text-center">
      <button type="button" class="btn btn-dark"><a href="{% url 'matkul:addMatkul' %}">Tambahkan Jadwal</a></button>
    </div>
  </div>

 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

personalwebsite/templates/personalwebsite/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <!-- CSS CDN BLOCK-->
    {% block linkCDN %} {% endblock linkCDN %}
    
    <!--Link Font-->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,900;1,500;1,700;1,900&family=Sansita+Swashed:wght@600;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,700;1,700&family=Sansita+Swashed:wght@800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,900;1,500;1,700;1,900&family=Sansita+Swashed:wght@600;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,900;1,500;1,700;1,900&family=Sansita+Swashed:wght@600;800&display=swap" rel="stylesheet">

    <!--CSS-->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!--Icon-->
    <link rel="icon" type="image/png" href="{% static 'logo.png' %}">

    <title>Futuh's Personal Website</title>
  </head>
  <body>
    
    <!-- Navigation Bar -->
    <div class="offset-1 col-10 text-center ">
        <nav class="navbar fixed-top navbar-expand-lg navbar">
        <a class="navbar-brand active" id="namaprofil" href="{% url 'personalwebsite:welcome' %}">Futuh's</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" id="navhome" href="{% url 'personalwebsite:profile' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'personalwebsite:profile' %}#about">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'personalwebsite:profile' %}#education">Education</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'personalwebsite:profile' %}#skill">Skills</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'personalwebsite:profile' %}#contact">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'story1:story1' %}">Story 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'matkul:listMatkul' %}">Story 5</a>
            </li>
            
            </ul>
        </div>
        </nav>
    </div>


    <!-- Block Main -->
    {% block main %} {% endblock main %}
                 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

personalwebsite/templates/personalwebsite/experience.html
{% extends 'personalwebsite/base.html' %} {% load static %}

{% block linkCDN %}
  <!--Link Font-->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,900;1,500;1,700;1,900&family=Sansita+Swashed:wght@600;800&display=swap" rel="stylesheet">
{% endblock linkCDN %}
  
    
{% block main %}
        <!--Experience-->
        <section class="experience" id="experience">
            <div class="container mt-5">
              <div class="row mt-5 mb-5">
                <div class="col-md-12 text-center">
                  <h1>Futuh's Random Things</h1>
                </div>
              </div>
              <div class="row justify-content-center">
                <div class=col-md-12>
                  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
                    </ol>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <center>
                        <video width="960" height="540" controls autoplay>
                          <source src="{% static 'Woe is me.mp4' %}" type="video/mp4"> </source>
                        </video><center>
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" width="960" height="540" src="{% static 'exp.JPG' %}" alt="First slide">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" width="960" height="540" src="{% static 'exp2.JPG' %}" alt="Second slide">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" width="960" height="540" src="{% static 'exp3.jpg' %}" alt="Third slide">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" width="960" height="540" src="{% static 'exp4.png' %}" alt="Fourth slide">
                      </div>
                      <div class="carousel-item">
                        <img class="d-block w-100" width="960" height="540" src="{% static 'exp5.png' %}" alt="Fifth slide">
                      </div>
                    </div>

                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
                </div>
              </div>

              <div class="row justify-content-center">
                <div class="col-md-12 text-center">
                  <a id="btnexp" class="btn btn-dark btn-lg" href="{% url 'personalwebsite:profile' %}#skill" role="button">Go Back!</a>
                </div>
              </div>
            </div>
          </section>

{% endblock main %}


    

personalwebsite/templates/personalwebsite/welcome.html
{% extends 'personalwebsite/base.html' %} {% load static %}

    <!-- CSS CDN BLOCK-->
    {% block linkCDN %}
       <!--Link Font-->
       <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,700;1,700&family=Sansita+Swashed:wght@800&display=swap" rel="stylesheet">
    {% endblock linkCDN %}
 



{% block main %}
    <div class="bg">
      <div class="welcome">
        <div id="wlcm" class="centered text-center">
          Welcome!<br>
          <a class="btn btn-dark btn-lg" href="{% url 'personalwebsite:profile' %}" role="button">Let's Get Started</a>
        </div>
      </div>
    </div>

{% endblock main %}